"""Flow for updating song data in the database.

This module contains tasks and flows for extracting song information from HTML,
parsing it into structured data, and inserting it into the database.
"""

import duckdb
import polars as pl
from bs4 import BeautifulSoup, ResultSet, Tag
from prefect import flow, task
from prefect.cache_policies import NO_CACHE

from models import Song


@task
def extract_song_elements(soup: BeautifulSoup) -> ResultSet[Tag]:
    """Extract song elements from the HTML page.

    Args:
        soup: BeautifulSoup object containing the parsed HTML.

    Returns:
        ResultSet of HTML elements containing song information.

    Uses CSS selector '.songName' to find song containers.

    """
    return soup.css.select('.songName')


@task(cache_policy=NO_CACHE)
def parse_song_data(soup: ResultSet[Tag]) -> list[Song]:
    """Parse song data from HTML elements into structured entries.

    Extracts artist and song name from webpage HTML and creates Song objects.

    Args:
        soup: ResultSet containing song HTML elements.

    Returns:
        List of Song objects with parsed artist and song information.

    """
    songs = soup

    song_list: list[Song] = []

    for song in songs:
        web_songname: str = song.text
        artist, song_name = web_songname.split(' - ', 1)
        song_list.append(
            Song(
                artist=artist,
                song_name=song_name,
                web_songname=web_songname,
            )
        )

    return song_list


@task
def create_songs_df(song_list: list[Song]) -> pl.DataFrame:
    """Convert list of Song objects to a Polars DataFrame.

    Args:
        song_list: List of Song objects to convert.

    Returns:
        Polars DataFrame containing song data.

    Drops 'id' column as it's auto-generated by database.

    """
    web_songs = pl.DataFrame(song_list)
    web_songs = web_songs.drop('id')
    return web_songs


@task
def insert_songs_into_db(_new_songs: pl.DataFrame, db_path: str) -> None:
    """Insert new songs into the database.

    Uses 'insert or ignore' to avoid duplicates.

    Args:
        _new_songs: DataFrame containing songs to insert.
        db_path: Path to DuckDB database.

    """
    with duckdb.connect(db_path) as conn:
        conn.execute(
            """-- sql
            insert or ignore into songs (artist, song_name, web_songname) (
                select * from _new_songs
            )
            """
        )


@flow
def update_songs_flow(soup: BeautifulSoup, db_path: str) -> None:
    """Complete workflow for updating song data in the database.

    Extracts song elements from HTML, parses them into structured data,
    and inserts new songs into the database.

    Args:
        soup: BeautifulSoup object containing the parsed HTML.
        db_path: Path to DuckDB database.

    """
    song_soup = extract_song_elements(soup=soup)
    songs = parse_song_data(soup=song_soup)
    songs_df = create_songs_df(songs)
    insert_songs_into_db(songs_df, db_path)
